### PR TITLE
Improve: Decimal number support (and other attributes too)

### PR DESCRIPTION
**Pull request by 3lvis**
This PR finally unit tests all the possible changes for Core Data attributes. Some attributes haven't been tested before such as decimal, float and double. This fixes that.

### CODE REVIEW

**Comment by wh33ler** [comment]
I just want to point out, that you should not cast a decimal value from NSNumber to NSDecimalNumber, because it might just be wrong as pointed out in this issue: http://stackoverflow.com/questions/31012902/nsnumber-to-nsdecimalnumber-conversion-issue

The only save way to transport a decimal is by string. Maybe you can add this casting option as well into your code

**Comment by 3lvis** [comment]
>I just want to point out, that you should not cast a decimal value from NSNumber to NSDecimalNumber

Hi Thomas,

I can't seem to find the mentioned casting, is there a specific line of code you're referring too?

I added a few additional tests to make sure that the returned decimals are of NSDecimalNumber class.

**Comment by wh33ler** [comment]
ok. My mistake. I thought you just added the NSNumber version only. But I just found the NSString conversion as well. So I guess this is perfect now. Thanks for your fast release.

**Comment by 3lvis** [comment]
@wh33ler Thanks again for pointing out this issue. I should use NSDecimalNumber more often! :grin:

**Pull request merged**
