### PR TITLE
Improve inflection methods

### LINKED ISSUE #139: hyp_dictionary(.camelCase) not affected to related entity
```swift
let entityCamel = workout?.hyp_dictionary(.camelCase)
print("CAMEL Cased: \(String(data: try! JSONSerialization.data(withJSONObject: entityCamel!, options: .prettyPrinted), encoding: .utf8)!)")
```
```json
CAMEL Cased: {
  "workoutName" : "Workout",
  "_id" : "FowQzznecDMvymf5g",
  "workout_exercises_attributes" : {
    "0" : {
      "exercise_name" : "Энергичная растяжка грудных мышц",
      "_id" : "WWeyhPHuuXr3LEHTo",
      "exercise_desc" : "<li>Станьте прямо, вытяните руки перед собой и соедините ладони так, как это показано на рисунке. Это будет вашим исходным положением.<\/li><li>Продолжая держать руки выпрямленными, отведите их назад, насколько это возможно и верните в исходное положение. Повторите 5-10 раз, увеличивая скорость.<\/li>",
      "main_muscle" : "Грудь",
      "exercise_sets_attributes" : {
        "0" : {
          "set_number" : 0,
          "is_completed" : 1,
          "_id" : "lDpmUg4TfuVnW0cL3",
          "set_reps" : 7,
          "set_weight" : 8
        }
      }
    },
    "1" : {
      "exercise_name" : "Эллиптический тренажер",
      "_id" : "3zHjHQbFiKR4eRjH2",
      "exercise_desc" : "<li>Станьте на эллиптический тренажер и выберите желаемую программу для тренировки. Опции большинства подобных тренажеров можно настроить вручную. Обычно требуется ввести ваш возраст и вес для оценки потерянных калорий во время тренировки. Уровень сложности может быть изменен вручную в любой момент.<\/li><li>Возьмитесь за рукоятки тренажера, чтобы вы смогли увидеть частоту сердечного ритма на мониторе и выбрать необходимую интенсивность тренировки.<\/li>",
      "main_muscle" : "Квадрицепсы",
      "exercise_sets_attributes" : {
        "0" : {
          "set_number" : 0,
          "is_completed" : 1,
          "_id" : "MTBigRc7dQ2qWm7NF",
          "set_reps" : 5,
          "set_weight" : 11
        }
      }
    }
  },
  "workoutDesc" : "<p><br><\/p>"
}
```
Related entities `workout` ->`workoutExercises` and `workout` ->`workoutExercises`->`exerciseSets` are `snakeCase`ed

### LINKED ISSUE #140: hyp_dictionary combine case and type for related attributes
It would be great to combine several attributes, for example `case` for entities and `type` for relation in one expression
```swift
let entityJSON = entity.hyp_dictionary(.camelCase)
let entityJSON = entity.hyp_dictionary(using: .array)
```
to
```swift
let entityJSON = entity.hyp_dictionary(attributes: [RelationType: .array, CaseType: .camelCase])
```

### PR DESCRIPTION
**Pull request by 3lvis**
Can be used as 

```swift
let result = user.hyp_dictionary(using: .snakeCase, andRelationshipType: .array)
```

- Fixes #139 
- Fixes #140

### CODE REVIEW

**Comment by 3lvis** [comment]
screen shot 2016-11-13 at 5 34 56 pm

**Comment by achirkof** [comment]
Wow! I will go to test.

**Comment by achirkof** [comment]
@3lvis it is strange but not all names are `camelCase`ed:

```json
COMPLETED WORKOUT: {
  "workoutName" : "Workout",
  "planned_to_ids" : [],
  "_id" : "FowQzznecDMvymf5g",
  "workoutexercises" : [
    {
      "exerciseName" : "",
      "_id" : "WWeyhPHuuXr3LEHTo",
      "exerciseDesc" : "",
      "mainMuscle" : "",
      "exercise_sets" : [
        {
          "_id" : "dAP4PF52TYRhT3CyF",
          "isCompleted" : 1,
          "setNumber" : 1,
          "setWeight" : 19.5,
          "setReps" : 7
        },
        {
          "_id" : "RHAF217QJRajfkhm3",
          "isCompleted" : 1,
          "setNumber" : 0,
          "setWeight" : 7.5,
          "setReps" : 5
        }
      ]
    },
    {
      "exerciseName" : "",
      "_id" : "3zHjHQbFiKR4eRjH2",
      "exerciseDesc" : "",
      "mainMuscle" : "",
      "exercise_sets" : [
        {
          "_id" : "v417PK8MlI28uwBdO",
          "isCompleted" : 1,
          "setNumber" : 0,
          "setWeight" : 5.5,
          "setReps" : 9
        }
      ]
    }
  ],
  "workoutDesc" : "<p><br><\/p>"
}
```

Field `workoutexercises` which is relation to **Exercise** model is not cased. Also `planned_to_ids` and `exercise_sets` are `snake_case`ed also relation fields.

Here is my model
image 2016-11-13 at 8 13 03 pm

**Comment by 3lvis** [comment]
Any of this have custom remote keys?

https://github.com/SyncDB/SYNCPropertyMapper#custom

**Comment by achirkof** [comment]
Only one field have no custom key

`eventSourceID` -> `plannedToIDs`
image 2016-11-13 at 10 02 56 pm

but other not.

**Comment by 3lvis** [comment]
@achirkof thanks a lot for your help testing this out.

Could you check again? I added some unit tests and improvements.

https://github.com/SyncDB/SYNCPropertyMapper/pull/142

**Comment by achirkof** [comment]
Looks like nothing changed:

**CAMEL Cased:**
```json 
{
  "workoutName" : "Workout",
  "planned_to_ids" : [],
  "_id" : "FowQzznecDMvymf5g",
  "workout_exercises" : [
    {
      "exerciseName" : "",
      "_id" : "WWeyhPHuuXr3LEHTo",
      "exerciseDesc" : "",
      "mainMuscle" : "",
      "exercise_sets" : [
        {
          "_id" : "3K4ZiTnvJFbnYH6Jd",
          "isCompleted" : 1,
          "setNumber" : 0,
          "setWeight" : 2.5,
          "setReps" : 5
        },
        {
          "_id" : "aVZAasaevTf8Fc9Nw",
          "isCompleted" : 1,
          "setNumber" : 1,
          "setWeight" : 4.5,
          "setReps" : 10
        }
      ]
    },
    {
      "exerciseName" : "",
      "_id" : "3zHjHQbFiKR4eRjH2",
      "exerciseDesc" : "<",
      "mainMuscle" : "",
      "exercise_sets" : [
        {
          "_id" : "sRkd2urobC2zvh0f9",
          "isCompleted" : 1,
          "setNumber" : 0,
          "setWeight" : 7,
          "setReps" : 5
        }
      ]
    }
  ],
  "workoutDesc" : "<p><br><\/p>"
}
```

**SNAKE Cased:**
```json
{
  "planned_to_ids" : [

  ],
  "_id" : "FowQzznecDMvymf5g",
  "workout_desc" : "<p><br><\/p>",
  "workout_name" : "Workout",
  "workout_exercises" : [
    {
      "exercise_name" : "",
      "_id" : "WWeyhPHuuXr3LEHTo",
      "exercise_desc" : "",
      "main_muscle" : "",
      "exercise_sets" : [
        {
          "set_number" : 0,
          "is_completed" : 1,
          "_id" : "3K4ZiTnvJFbnYH6Jd",
          "set_reps" : 5,
          "set_weight" : 2.5
        },
        {
          "set_number" : 1,
          "is_completed" : 1,
          "_id" : "aVZAasaevTf8Fc9Nw",
          "set_reps" : 10,
          "set_weight" : 4.5
        }
      ]
    },
    {
      "exercise_name" : "",
      "_id" : "3zHjHQbFiKR4eRjH2",
      "exercise_desc" : "",
      "main_muscle" : "",
      "exercise_sets" : [
        {
          "set_number" : 0,
          "is_completed" : 1,
          "_id" : "sRkd2urobC2zvh0f9",
          "set_reps" : 5,
          "set_weight" : 7
        }
      ]
    }
  ]
}
```
You cat take [my project](https://drive.google.com/file/d/0B-LbbHDmW7zWMTZXYTVFZU1uTTQ/view?usp=sharing) and check.

**Comment by achirkof** [comment]
Hi @3lvis ! Have idea why export not fully `camelCsed`?

**Comment by 3lvis** [comment]
@achirkof Hi! I haven't had enough time to look closely into this. I'll see what I can do :)

**Pull request merged**
