### PR TITLE
Bug 112

### PR DESCRIPTION
**Pull request by 3lvis**
Fixes https://github.com/hyperoslo/NSManagedObject-HYPPropertyMapper/issues/112

### CODE REVIEW

**Comment by Sorix** [comment]
You have added only test cases here?

**Comment by 3lvis** [comment]
@Sorix yes, this was before we agreed on what would be the solution. :)

**Comment by 3lvis** [comment]
Feel free to submit a PR completing this using the `hyper.nonExportable` key. I'm quite busy this days and will only have time to look into this in the weekend.

**Comment by Sorix** [comment]
I don’t know Objective-C well, working only with Swift, so I can’t PR it, sorry

**Comment by 3lvis** [comment]
@Sorix That's fine, thanks. I'll see if I can have a look later. Still busy days, can't wait to shit the app I'm working on :)

**Comment by 3lvis** [comment]
screen shot 2016-09-22 at 19 27 40

**Pull request merged**
