### PR TITLE
Adding support for flattening out deep JSON structures with keyPaths

### PR DESCRIPTION
**Pull request by marthinfreij**
This implements https://github.com/hyperoslo/Sync/issues/274

### CODE REVIEW

**Comment by 3lvis** [comment]
Btw, do you have this checkbox? 

01fa90ba-7443-11e6-952f-a35a34d07c62

**Comment by 3lvis** [comment]
2b17b4c2-7444-11e6-8959-2f7ed2012d07

**Comment by marthinfreij** [comment]
Yes, it's checked

**Comment by marthinfreij** [comment]
Just saw that my last commit broke the tests. Working on that.

**Comment by marthinfreij** [comment]
I don't get why the tests fail? Some cocoapod issue?

**Comment by 3lvis** [comment]
If they pass locally then it should be enough :)

**Comment by 3lvis** [comment]
Moved here https://github.com/hyperoslo/NSManagedObject-HYPPropertyMapper/pull/116

**Pull request merged**
