### PR TITLE
Remote keys

### PR DESCRIPTION
**Pull request by 3lvis**

### CODE REVIEW

**Comment by NSElvis** [comment]
I fixed the tests but there's still the problem that @RamonGilabert pointed out, `hyp_fillWithDictionary` works, but `hyp_dictionary` doesn't work.

**Comment by NSElvis** [comment]
@RamonGilabert: please make sure to check for the custom key when doing `hyp_dictionary` :)

**Comment by NSElvis** [comment]
The tests should be in place for this functionality

**Comment by NSElvis** [comment]
for `hyp_fillWithDictionary` you transform the custom key, to local
for `hyp_dictionary` you just use the custom key

**Comment by NSElvis** [comment]
@RamonGilabert: `hyp_fillWithDictionary` it's been fine, it's `hyp_dictionary` what was failing

**Comment by NSElvis** [comment]
@RamonGilabert: it's passing! :tada: :tada: :tada: :tada:

**Comment by RamonGilabert** [comment]
@NSElvis nice! :dancer: :dancer:

**Pull request merged**
