### PR TITLE
bugfix for #68

### PR DESCRIPTION
**Pull request by sononum**
taken from https://github.com/soffes/SAMCategories/blob/master/SAMCategories/NSDate%2BSAMAdditions.m

### CODE REVIEW

**Comment by 3lvis** [comment]
Thanks Ulrich! Would you mind adding a few test cases testing what is supposed to be fixed?

**Comment by 3lvis** [comment]
This could be very useful to test regressions and make sure your additions don't get rolled back.

**Comment by sononum** [comment]
I'll do, I'm currently using Sync without CocoaPods it will take a while to get the tests running...

**Comment by 3lvis** [comment]
@sononum I see, I can add a few test cases for you. Can you provide me some date examples that this is supposed to fix?

**Comment by sononum** [comment]
I have created one in my project, I hope it builds in the pods project:

```objc
- (void)testBornDateWithMilliseconds {
    NSDictionary *values = @{@"birth_date" : @"2015-06-23T12:40:08.000+02:00"};

    DATAStack *dataStack = [DATAStack sharedStack];
    User *user = [self userUsingDataStack:dataStack];

    [user hyp_fillWithDictionary:values];

    NSDateFormatter *dateFormat = [[NSDateFormatter alloc] init];
    dateFormat.dateFormat = @"yyyy-MM-dd'T'HH:mm:ss.SSS'Z'";
    dateFormat.timeZone = [NSTimeZone timeZoneForSecondsFromGMT:2*60*60];
    NSDate *date = [dateFormat dateFromString:@"2015-06-23T12:40:08.594"];

    XCTAssertNotNil([user valueForKey:@"birthDate"]);
    XCTAssertEqualWithAccuracy([[user valueForKey:@"birthDate"] timeIntervalSinceReferenceDate], date.timeIntervalSinceReferenceDate, 1.);
}
```

**Comment by sononum** [comment]
I just saw:

``` objc
NSDate *date = [dateFormat dateFromString:@"2015-06-23T12:40:08.594"];
```

should be

```objc
NSDate *date = [dateFormat dateFromString:@"2015-06-23T12:40:08.000"];
```
the .594 is confusing...

**Pull request merged**
